wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    code_path: code/main.py
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1686355312.221166
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.9.7
      5: 0.14.0
      8:
      - 1
      - 5
env_seed:
  desc: null
  value: 100
name_model:
  desc: null
  value: PPO
name_reward:
  desc: null
  value: NumTreesRewardStepOne
ncols:
  desc: null
  value: 10
nrows:
  desc: null
  value: 10
obs_wrapper:
  desc: null
  value: ObservationOneHotWrapper_dict_box
policy_type:
  desc: null
  value: MultiInputPolicy
pos_bull:
  desc: null
  value:
  - 9
  - 9
pos_fire:
  desc: null
  value:
  - 5
  - 0
steps_threshold:
  desc: null
  value: 1000
t_any:
  desc: null
  value: 0.025
t_move:
  desc: null
  value: 0.025
t_shoot:
  desc: null
  value: 0.1
total_proces:
  desc: null
  value: 8
