wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True  True  True  True  True]'
_last_obs:
  desc: null
  value: "OrderedDict([('grid', array([[[[0, 0, 0, ..., 1, 1, 1],\n         [0, 0,\
    \ 0, ..., 1, 1, 1],\n         [0, 0, 0, ..., 1, 0, 1],\n         ...,\n      \
    \   [0, 0, 1, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 1, 1, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 1]]],\n\n\n       [[[0, 0, 0, ..., 1, 1, 1],\n         [0,\
    \ 0, 0, ..., 1, 1, 1],\n         [0, 0, 0, ..., 1, 0, 1],\n         ...,\n   \
    \      [0, 0, 1, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 1, 1, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 1]]],\n\n\n       [[[0, 0, 0, ..., 1, 1, 1],\n         [0,\
    \ 0, 0, ..., 1, 1, 1],\n         [0, 0, 0, ..., 1, 0, 1],\n         ...,\n   \
    \      [0, 0, 1, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 1, 1, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 1]]],\n\n\n       ...,\n\n\n       [[[0, 0, 0, ..., 1, 1, 1],\n\
    \         [0, 0, 0, ..., 1, 1, 1],\n         [0, 0, 0, ..., 1, 0, 1],\n      \
    \   ...,\n         [0, 0, 1, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n\
    \         [0, 0, 0, ..., 1, 1, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n   \
    \      [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n\
    \         [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n      \
    \   [0, 0, 0, ..., 0, 0, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n   \
    \      [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 1]]],\n\n\n       [[[0, 0, 0, ..., 1, 1, 1],\n         [0,\
    \ 0, 0, ..., 1, 1, 1],\n         [0, 0, 0, ..., 1, 0, 1],\n         ...,\n   \
    \      [0, 0, 1, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 1, 1, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 1]]],\n\n\n       [[[0, 0, 0, ..., 1, 1, 1],\n         [0,\
    \ 0, 0, ..., 1, 1, 1],\n         [0, 0, 0, ..., 1, 0, 1],\n         ...,\n   \
    \      [0, 0, 1, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 1, 1, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 0]],\n\n        [[0, 0, 0, ..., 0, 0, 0],\n         [0, 0,\
    \ 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         ...,\n      \
    \   [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 1]]]], dtype=int8)), ('time', array([[0.],\n       [0.],\n\
    \       [0.],\n       [0.],\n       [0.],\n       [0.],\n       [0.],\n      \
    \ [0.]], dtype=float32))])"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f0f22483880>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 3000000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    code_path: code/main.py
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    session_history: code/_session_history.ipynb
    start_time: 1686587717.322976
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 16
      - 22
      - 23
      - 34
      4: 3.9.7
      5: 0.14.0
      8:
      - 1
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: MultiDiscrete([9 2])
algo:
  desc: null
  value: PPO
batch_size:
  desc: null
  value: 64
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f0f206d1310>
clip_range_vf:
  desc: null
  value: None
device:
  desc: null
  value: cuda
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f0f20332940>
env_seed:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.0003
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f0f206d13a0>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 8
n_epochs:
  desc: null
  value: 10
n_steps:
  desc: null
  value: 2048
name_model:
  desc: null
  value: PPO
name_reward:
  desc: null
  value: NumTreesRewardStepOne
ncols:
  desc: null
  value: 10
normalize_advantage:
  desc: null
  value: 'True'
nrows:
  desc: null
  value: 10
num_timesteps:
  desc: null
  value: 0
obs_wrapper:
  desc: null
  value: ObservationOneHotWrapper_dict_box
observation_space:
  desc: null
  value: Dict(grid:MultiBinary([3, 10, 10]), time:Box([0.], [1.], (1,), float32))
policy:
  desc: null
  value: "MultiInputActorCriticPolicy(\n  (features_extractor): CombinedExtractor(\n\
    \    (extractors): ModuleDict(\n      (grid): Flatten(start_dim=1, end_dim=-1)\n\
    \      (time): Flatten(start_dim=1, end_dim=-1)\n    )\n  )\n  (pi_features_extractor):\
    \ CombinedExtractor(\n    (extractors): ModuleDict(\n      (grid): Flatten(start_dim=1,\
    \ end_dim=-1)\n      (time): Flatten(start_dim=1, end_dim=-1)\n    )\n  )\n  (vf_features_extractor):\
    \ CombinedExtractor(\n    (extractors): ModuleDict(\n      (grid): Flatten(start_dim=1,\
    \ end_dim=-1)\n      (time): Flatten(start_dim=1, end_dim=-1)\n    )\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (shared_net): Sequential()\n    (policy_net): Sequential(\n\
    \      (0): Linear(in_features=301, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n    (value_net): Sequential(\n      (0): Linear(in_features=301, out_features=64,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (3): Tanh()\n    )\n  )\n  (action_net): Linear(in_features=64,\
    \ out_features=11, bias=True)\n  (value_net): Linear(in_features=64, out_features=1,\
    \ bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.MultiInputActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{}'
policy_type:
  desc: null
  value: MultiInputPolicy
pos_bull:
  desc: null
  value:
  - 9
  - 9
pos_fire:
  desc: null
  value:
  - 4
  - 5
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.DictRolloutBuffer object at 0x7f0f206ce490>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1686587724077871995
steps_threshold:
  desc: null
  value: 3000000
t_any:
  desc: null
  value: 0.025
t_move:
  desc: null
  value: 0.2
t_shoot:
  desc: null
  value: 0.025
target_kl:
  desc: null
  value: None
tensorboard_log:
  desc: null
  value: runs/6spqx3ii
total_proces:
  desc: null
  value: 8
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
vf_coef:
  desc: null
  value: 0.5
